#!/usr/bin/env python

import chess
import chess.polyglot
import threading
import time
import sys


MAX_SCORE = 100000
MOVES_TO_ENDGAME = 30

ttDEPTH, ttFLAG, ttVALUE = 0, 1, 2
ttEXACT, ttLOWERBOUND, ttUPPERBOUND = 0, 1, 2
TRANSPOSITION_TABLE_SIZE = 0x100000

POSITION_VALUES = [
    # King (end game)
    [
    -50,-40,-30,-20,-20,-30,-40,-50,
    -30,-20,-10,  0,  0,-10,-20,-30,
    -30,-10, 20, 30, 30, 20,-10,-30,
    -30,-10, 30, 40, 40, 30,-10,-30,
    -30,-10, 30, 40, 40, 30,-10,-30,
    -30,-10, 20, 30, 30, 20,-10,-30,
    -30,-30,  0,  0,  0,  0,-30,-30,
    -50,-30,-30,-30,-30,-30,-30,-50,
    ],
    # Pawn
    [
    0,  0,  0,  0,  0,  0,  0,  0,
    50, 50, 50, 50, 50, 50, 50, 50,
    10, 10, 20, 30, 30, 20, 10, 10,
     5,  5, 10, 25, 25, 10,  5,  5,
     0,  0,  0, 20, 20,  0,  0,  0,
     5, -5,-10,  0,  0,-10, -5,  5,
     5, 10, 10,-20,-20, 10, 10,  5,
     0,  0,  0,  0,  0,  0,  0,  0,
     ],
    # Knight
    [
    -50,-40,-30,-30,-30,-30,-40,-50,
    -40,-20,  0,  0,  0,  0,-20,-40,
    -30,  0, 10, 15, 15, 10,  0,-30,
    -30,  5, 15, 20, 20, 15,  5,-30,
    -30,  0, 15, 20, 20, 15,  0,-30,
    -30,  5, 10, 15, 15, 10,  5,-30,
    -40,-20,  0,  5,  5,  0,-20,-40,
    -50,-40,-30,-30,-30,-30,-40,-50,
    ],
    # Bishop
    [
    -20,-10,-10,-10,-10,-10,-10,-20,
    -10,  0,  0,  0,  0,  0,  0,-10,
    -10,  0,  5, 10, 10,  5,  0,-10,
    -10,  5,  5, 10, 10,  5,  5,-10,
    -10,  0, 10, 10, 10, 10,  0,-10,
    -10, 10, 10, 10, 10, 10, 10,-10,
    -10,  5,  0,  0,  0,  0,  5,-10,
    -20,-10,-10,-10,-10,-10,-10,-20,
    ],
    # Rook
    [
     0,  0,  0,  0,  0,  0,  0,  0,
     5, 10, 10, 10, 10, 10, 10,  5,
    -5,  0,  0,  0,  0,  0,  0, -5,
    -5,  0,  0,  0,  0,  0,  0, -5,
    -5,  0,  0,  0,  0,  0,  0, -5,
    -5,  0,  0,  0,  0,  0,  0, -5,
    -5,  0,  0,  0,  0,  0,  0, -5,
     0,  0,  0,  5,  5,  0,  0,  0,
    ],
    # Queen
    [
    -20,-10,-10, -5, -5,-10,-10,-20,
    -10,  0,  0,  0,  0,  0,  0,-10,
    -10,  0,  5,  5,  5,  5,  0,-10,
     -5,  0,  5,  5,  5,  5,  0, -5,
      0,  0,  5,  5,  5,  5,  0, -5,
    -10,  5,  5,  5,  5,  5,  0,-10,
    -10,  0,  5,  0,  0,  0,  0,-10,
    -20,-10,-10, -5, -5,-10,-10,-20,
    ],
    # King
    [
    -30,-40,-40,-50,-50,-40,-40,-30,
    -30,-40,-40,-50,-50,-40,-40,-30,
    -30,-40,-40,-50,-50,-40,-40,-30,
    -30,-40,-40,-50,-50,-40,-40,-30,
    -20,-30,-30,-40,-40,-30,-30,-20,
    -10,-20,-20,-20,-20,-20,-20,-10,
     20, 20,  0,  0,  0,  0, 20, 20,
     20, 30, 10,  0,  0, 10, 30, 20,
    ],
]

# [King (end game), Pawn, Knight, Bishop, Rook, Queen, King]
PIECE_VALUES = [0, 100, 320, 330, 500, 900, 0]


class BlueRose:
    def __init__(self):
        self.board = chess.Board()
        self.transposition_table = []

    def transposition_table_clear(self):
        self.transposition_table = [0]*TRANSPOSITION_TABLE_SIZE

    def board_evaluation(self):
        score = 0
        for square, piece in self.board.piece_map().items():
            pt = piece.piece_type
            if pt == chess.KING and self.board.fullmove_number > MOVES_TO_ENDGAME:
                pt = 0
            color = 1 if piece.color else -1

            piece_value = PIECE_VALUES[pt]
            position_adjustment = POSITION_VALUES[pt][square]
            score += color * (piece_value + position_adjustment)

        return score

    def transposition_table_lookup(self):
        zhash = chess.polyglot.zobrist_hash(self.board) & (TRANSPOSITION_TABLE_SIZE - 1)
        if self.transposition_table[zhash] != 0:
            return self.transposition_table[zhash], zhash
        else:
            return None, zhash

    def negamax(self, depth, alpha, beta, time_limit):
        global nodes
        nodes += 1

        global kill_search
        if kill_search or time.time() > time_limit:
            return None

        alphaOrig = alpha

        ttEntry, zhash = self.transposition_table_lookup()
        if ttEntry and ttEntry[ttDEPTH] >= depth:
            if ttEntry[ttFLAG] == ttEXACT:
                return ttEntry[ttVALUE]
            elif ttEntry[ttFLAG] == ttLOWERBOUND:
                alpha = max(alpha, ttEntry[ttVALUE])
            elif ttEntry[ttFLAG] == ttUPPERBOUND:
                beta = min(beta, ttEntry[ttVALUE])

            if alpha >= beta:
                return ttEntry[ttVALUE]

        if self.board.is_checkmate():
            return -MAX_SCORE

        if self.board.is_stalemate():
            return 0

        if self.board.is_insufficient_material():
            return 0

        if self.board.is_repetition(3):
            return 0

        if depth == 1:
            score = self.board_evaluation()
            if not self.board.turn:
                score = -score

            return score

        best_score = -MAX_SCORE - 1

        for move in self.board.legal_moves:
            self.board.push(move)
            value = self.negamax(depth - 1, -beta, -alpha, time_limit)
            self.board.pop()

            if value is None:
                return None

            best_score = max(best_score, -value)

            alpha = max(best_score, alpha)
            if alpha >= beta:
                break

        new_ttEntry = [0, 0, 0]
        new_ttEntry[ttVALUE] = best_score
        if best_score <= alphaOrig:
            new_ttEntry[ttFLAG] = ttUPPERBOUND
        elif best_score >= beta:
            new_ttEntry[ttFLAG] = ttLOWERBOUND
        else:
            new_ttEntry[ttFLAG] = ttEXACT
        new_ttEntry[ttDEPTH] = depth
        self.transposition_table[zhash] = new_ttEntry

        return best_score

    def MTDf(self, depth, first_guess, time_limit):
        g = first_guess
        upperbound = MAX_SCORE
        lowerbound = -MAX_SCORE
        while lowerbound < upperbound:
            beta = max(g, lowerbound + 1)
            g = -self.negamax(depth, beta - 1, beta, time_limit)
            if g is None:
                return None

            if g < beta:
                upperbound = g
            else:
                lowerbound = g

        return g

    def iterative_deepening(self, move_time, max_depth):
        self.transposition_table_clear()

        t1 = time.time()
        time_limit = t1 + move_time
        color = [-1, 1][self.board.turn]

        best_move = list(self.board.legal_moves)[0]

        global nodes
        nodes = 0

        depth = 1
        first_guess = 0
        while True:
            best_score = -MAX_SCORE - 1
            for move in self.board.legal_moves:
                self.board.push(move)
                first_guess = self.MTDf(depth, first_guess, time_limit)
                self.board.pop()
                if first_guess is None:
                    return best_move

                if first_guess > best_score:
                    best_score = first_guess
                    best_move = move

            time_ms = int((time.time() - t1) * 1000) + 1
            nps = int(nodes/time_ms * 1000)

            print(f'info depth {depth} multipv 1 score cp {color*best_score} nodes {nodes} nps {nps} time {time_ms} pv {self.board.uci(best_move)}', flush=True)

            if best_score == MAX_SCORE:
                return best_move

            depth += 1
            if max_depth > 0 and depth > max_depth:
                break

        return best_move

    def uci(self, command):
        if command == 'uci':
            print('id name BlueRose 1', flush=True)
            print('id author Brian Pomerantz', flush=True)
            print('uciok', flush=True)

        elif command == 'isready':
            print('readyok', flush=True)

        elif command == 'ucinewgame':
            self.board = chess.Board()

        elif 'position' in command:
            mi = -1
            if 'moves' in command:
                mi = command.index('moves') - 1
                fen = command[9:mi]
            else:
                fen = command[9:]

            if fen == 'startpos':
                fen = chess.STARTING_FEN

            self.board = chess.Board(fen)

            if mi != -1:
                moves_list = command[mi+1:].split()[1:]
                for move in moves_list:
                    move_obj = chess.Move.from_uci(move)
                    self.board.push(move_obj)

        elif 'go' in command:
            time_limit = 30*60
            depth = -1

            time_str = 'wtime' if self.board.turn else 'btime'
            if time_str in command:
                args = command.split()
                idx = args.index(time_str) + 1
                time_left = int(args[idx]) / 1000
                time_denom = MOVES_TO_ENDGAME
                if self.board.fullmove_number < 10:
                    time_denom *= 1.5
                time_limit = time_left // time_denom

            elif 'movetime' in command:
                time_limit = command.split()[2]
                time_limit = int(time_limit) // 1000 - 3

            elif 'depth' in command:
                depth = int(command.split()[2])

            move = self.iterative_deepening(time_limit, depth)
            print(f'bestmove {self.board.uci(move)}', flush=True)
            global kill_search
            kill_search = False


if __name__ == '__main__':
    print('BlueRose 1 by Brian Pomerantz', flush=True)
    engine = BlueRose()
    global kill_search
    kill_search = False

    if len(sys.argv) == 2 and sys.argv[1] == 'test':
        engine.uci('go depth 7')
        exit()

    while True:
        uci_input = input()
        if uci_input == 'stop':
            kill_search = True
            continue
        if uci_input == 'quit':
            break
        x = threading.Thread(target=engine.uci, args=(uci_input,), daemon=True)
        x.start()
